name: Docker Image CI

on:
  push:
    branches: [ master, prod ]
  pull_request:
    branches: [ master, prod ]
env:
  RC_NAME: davidtnfsh/dt42_piggy_front_end
jobs:

  build:

    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull cache
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker pull ${RC_NAME}:cache

    - name: Build the Docker image
      if: always()
      run: |
        docker build -t ${RC_NAME}:${GITHUB_SHA} --cache-from ${RC_NAME}:cache .
        docker tag ${RC_NAME}:${GITHUB_SHA} ${RC_NAME}:cache
        docker tag ${RC_NAME}:${GITHUB_SHA} ${RC_NAME}:staging
        docker tag ${RC_NAME}:${GITHUB_SHA} ${RC_NAME}:latest

    - name: Run test
      run: |
        docker run --rm -p 5000:5000 -itd ${RC_NAME}:${GITHUB_SHA}
        sleep 3
        curl -XGET http://localhost:5000
        [ $? -eq 0 ]  || exit 1

    - name: Push Cache to docker registry
      uses: actions-hub/docker@master
      if: always()
      with:
        args: push ${RC_NAME}:cache

    - name: Push GITHUB_SHA to docker registry
      uses: actions-hub/docker@master
      if: always()
      with:
        args: push ${RC_NAME}:${GITHUB_SHA}

    - name: Push staging to docker registry
      uses: actions-hub/docker@master
      if: github.ref == 'refs/heads/master' && success()
      with:
        args: push ${RC_NAME}:staging

    - name: Push prod version to docker registry
      uses: actions-hub/docker@master
      if: github.ref == 'refs/heads/prod' && success()
      with:
        args: push ${RC_NAME}:latest